services:

  tg_bot:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: tg_bot
    volumes: 
      - ./:/app
    depends_on:
      - tg_database
    env_file:
      - .env
    networks:
      - tg_jobb_bot_network


  tg_database:
    image: postgres:13
    container_name: tg_database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tg_jobb_bot_network
    env_file:
      - .env



  redis:
    image: redis:7-alpine
    container_name: tg_bot_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - tg_jobb_bot_network
    env_file:
      - .env


    



volumes: 
  postgres_data:

networks:
  tg_jobb_bot_network:
    driver: bridge