"""add jobb model

Revision ID: b26d78bccf00
Revises: afdd5a5c0629
Create Date: 2025-06-10 13:22:22.359398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b26d78bccf00'
down_revision: Union[str, None] = 'afdd5a5c0629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobb_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='jobb_priority'), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('applied', 'waiting_response', 'rejected', 'interview_1', 'interview_2', 'offer', name='job_status'), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobb_items_id'), 'jobb_items', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobb_items_id'), table_name='jobb_items')
    op.drop_table('jobb_items')
    # ### end Alembic commands ###
