"""models.py creation

Revision ID: fc4721bfcced
Revises: 9e76773fd540
Create Date: 2025-06-05 10:37:02.441530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc4721bfcced'
down_revision: Union[str, None] = '9e76773fd540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_name', sa.String(length=55), nullable=True),
    sa.Column('tg_user_id', sa.Integer(), nullable=True),
    sa.Column('user_login', sa.String(length=55), nullable=True),
    sa.Column('user_experience', sa.Float(), nullable=True),
    sa.Column('user_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_linkedin', sa.String(length=2048), nullable=True),
    sa.Column('user_git_hub', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_User_id'), 'User', ['id'], unique=False)
    op.create_index(op.f('ix_User_tg_user_id'), 'User', ['tg_user_id'], unique=True)
    op.create_index(op.f('ix_User_user_login'), 'User', ['user_login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_user_login'), table_name='User')
    op.drop_index(op.f('ix_User_tg_user_id'), table_name='User')
    op.drop_index(op.f('ix_User_id'), table_name='User')
    op.drop_table('User')
    # ### end Alembic commands ###
