"""models.py creation

Revision ID: 41672b600bfb
Revises: 
Create Date: 2025-06-16 19:24:15.324926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41672b600bfb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_user_name', sa.String(length=55), nullable=True),
    sa.Column('tg_user_id', sa.Integer(), nullable=True),
    sa.Column('user_login', sa.String(length=55), nullable=True),
    sa.Column('google_sheet_id', sa.String(length=100), nullable=True),
    sa.Column('google_sheet_url', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sheet_id'),
    sa.UniqueConstraint('google_sheet_url')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_tg_user_id'), 'user', ['tg_user_id'], unique=True)
    op.create_index(op.f('ix_user_user_login'), 'user', ['user_login'], unique=True)
    op.create_table('jobb_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='jobb_priority'), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('applied', 'waiting_response', 'rejected', 'interview_1', 'interview_2', 'offer', name='job_status'), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('additional_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobb_items_id'), 'jobb_items', ['id'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_experience', sa.Float(), nullable=True),
    sa.Column('user_languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_linkedin', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_git_hub', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hard_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('soft_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('education', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profile_id'), 'profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_jobb_items_id'), table_name='jobb_items')
    op.drop_table('jobb_items')
    op.drop_index(op.f('ix_user_user_login'), table_name='user')
    op.drop_index(op.f('ix_user_tg_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
